Repository cordada/lib-cl-sii-python, pull requests merged in 2019-07, with the labels that each got.

#69 libs.tz_utils: Fix setting of time zone information in datetimes
  cl_sii/libs/tz_utils.py
  cl_sii/rcv/data_models.py
Labels: bugfix, component: libs

#71 rut: Strip leading zeros from RUTs
  cl_sii/rut/__init__.py
  tests/test_rut.py
Labels: component: other, enhancement

#70 rut: Add less-than and greater-than methods
  cl_sii/rut/__init__.py
  tests/test_rut.py
Labels: component: other, feature

#72 extras: Handle `str`-typed RUTs in `Django RutField.get_prep_value()`
  cl_sii/extras/dj_model_fields.py
  tests/test_extras_dj_model_fields.py
Labels: component: other, enhancement

#73 Release v0.7.2
  .bumpversion.cfg
  HISTORY.rst
  cl_sii/__init__.py
  cl_sii/extras/dj_model_fields.py
  cl_sii/libs/tz_utils.py
  cl_sii/rcv/data_models.py
  cl_sii/rut/__init__.py
  requirements/release.txt
  requirements/test.txt
  scripts/clean_dte_xml_file.py
  tests/test_extras_dj_model_fields.py
  tests/test_libs_xml_utils.py
  tests/test_rut.py
Labels: kind: release

#74 requirements: update main packages
  requirements/base.txt
  setup.py
Labels: dependencies, task

#75 Release v0.7.3
  .bumpversion.cfg
  HISTORY.rst
  cl_sii/__init__.py
  requirements/base.txt
  setup.py
Labels: kind: release
