Repository cordada/lib-cl-sii-python, pull requests merged in 2019-10, with the labels that each got.

#86 add config file for "deepsource"
  .deepsource.toml
Labels: component: config

#88 update config file for "deepsource"
  .deepsource.toml
Labels: component: config

#87 cte: add data model, parser and more
  cl_sii/cte/__init__.py
  cl_sii/cte/f29/__init__.py
  cl_sii/cte/f29/data_models.py
  cl_sii/cte/f29/datos_obj.schema.json
  cl_sii/cte/f29/parse_datos_obj.py
  cl_sii/libs/json_utils.py
  requirements/base.txt
  setup.cfg
  setup.py
  tests/cte_f29_factories.py
  tests/test_cte_f29_data_models.py
  tests/test_cte_f29_parse_datos_obj.py
  tests/test_data/sii-cte/f29/cte--61002000-3--f29-6600000016-datos-obj-fake.json
  tests/test_libs_json_utils.py
  tests/utils.py
Labels: component: cte, dependencies, feature

#89 cte: Move JSON Schema of F29 'datos' object to 'data' directory and include it in the distribution packages
  MANIFEST.in
  cl_sii/cte/f29/parse_datos_obj.py
  cl_sii/data/cte/schemas-json/f29_datos_obj.schema.json
  setup.py
Labels: component: config, component: cte, feature

#90 Release v0.8.2
  .bumpversion.cfg
  .deepsource.toml
  HISTORY.rst
  MANIFEST.in
  cl_sii/__init__.py
  cl_sii/cte/__init__.py
  cl_sii/cte/f29/__init__.py
  cl_sii/cte/f29/data_models.py
  cl_sii/cte/f29/parse_datos_obj.py
  cl_sii/data/cte/schemas-json/f29_datos_obj.schema.json
  cl_sii/libs/json_utils.py
  requirements/base.txt
  setup.cfg
  setup.py
  tests/cte_f29_factories.py
  tests/test_cte_f29_data_models.py
  tests/test_cte_f29_parse_datos_obj.py
  tests/test_data/sii-cte/f29/cte--61002000-3--f29-6600000016-datos-obj-fake.json
  tests/test_libs_json_utils.py
  tests/utils.py
Labels: kind: release

#91 extras.mm_fields: add `RcvPeriodoTributarioField`
  cl_sii/extras/mm_fields.py
  tests/test_extras_mm_fields.py
Labels: component: other, component: rcv, feature
