Repository cordada/lib-cl-sii-python, pull requests merged in 2021-12, with the labels that each got.

#257 Release v0.15.1
  .bumpversion.cfg
  HISTORY.rst
  cl_sii/__init__.py
  requirements/base.txt
Labels: kind: release

#258 chore: Increase lxml lower bound constraint
  setup.py
Labels: topic: security, dependencies

#259 requirements: Update 'signxml'
  requirements/base.txt
  setup.py
Labels: dependencies

#260 Release v0.15.2
  .bumpversion.cfg
  HISTORY.rst
  cl_sii/__init__.py
  requirements/base.txt
  setup.py
Labels: kind: release

#261 chore(rtc.parse): Disable validation that AEC signature cert is loadable
  cl_sii/rtc/parse_aec.py
Labels: component: rtc, bugfix

#253 Rename of the enum class for `TipoDte` object
  cl_sii/dte/constants.py
  cl_sii/dte/data_models.py
  cl_sii/dte/parse.py
  cl_sii/extras/mm_fields.py
  cl_sii/rcv/constants.py
  cl_sii/rtc/constants.py
  cl_sii/rtc/data_models.py
  cl_sii/rtc/data_models_cesiones_periodo.py
  cl_sii/rtc/parse_aec.py
  tests/test_dte_constants.py
  tests/test_dte_data_models.py
  tests/test_dte_parse.py
  tests/test_extras_mm_fields.py
  tests/test_rcv_constants.py
  tests/test_rtc_data_models.py
  tests/test_rtc_data_models_aec.py
  tests/test_rtc_data_models_cesiones_periodo.py
  tests/test_rtc_parse_aec.py
Labels: task, component: dte

#262 Release v0.16.0
  .bumpversion.cfg
  HISTORY.rst
  cl_sii/__init__.py
  cl_sii/dte/constants.py
  cl_sii/dte/data_models.py
  cl_sii/dte/parse.py
  cl_sii/extras/mm_fields.py
  cl_sii/rcv/constants.py
  cl_sii/rtc/constants.py
  cl_sii/rtc/data_models.py
  cl_sii/rtc/data_models_cesiones_periodo.py
  cl_sii/rtc/parse_aec.py
  tests/test_dte_constants.py
  tests/test_dte_data_models.py
  tests/test_dte_parse.py
  tests/test_extras_mm_fields.py
  tests/test_rcv_constants.py
  tests/test_rtc_data_models.py
  tests/test_rtc_data_models_aec.py
  tests/test_rtc_data_models_cesiones_periodo.py
  tests/test_rtc_parse_aec.py
Labels: kind: release
