Repository cordada/lib-cl-sii-python, pull requests merged in 2021-02, with the labels that each got.

#186 rtc: Add methods to build CesionL2, CesionL1, and CesionL0 from other data models
  cl_sii/rtc/data_models.py
  cl_sii/rtc/data_models_aec.py
  tests/test_rtc_data_models.py
  tests/test_rtc_data_models_aec.py
Labels: component: rtc, feature

#187 Release v0.12.1
  .bumpversion.cfg
  HISTORY.rst
  cl_sii/__init__.py
  cl_sii/rtc/data_models.py
  cl_sii/rtc/data_models_aec.py
  tests/test_rtc_data_models.py
  tests/test_rtc_data_models_aec.py
Labels: kind: release

#192 Release v0.12.2
  .bumpversion.cfg
  HISTORY.rst
  cl_sii/__init__.py
  requirements/base.txt
  requirements/release.txt
  requirements/test.txt
Labels: kind: release

#193 requirements: Update dependency graph of base requirements
  requirements/base.txt
Labels: dependencies

#197 extras: add 'RutField' for Django forms
  cl_sii/extras/dj_form_fields.py
  tests/test_extras_dj_form_fields.py
Labels: component: other, feature

#198 Release v0.12.3
  .bumpversion.cfg
  HISTORY.rst
  cl_sii/__init__.py
  cl_sii/extras/dj_form_fields.py
  requirements/base.txt
  tests/test_extras_dj_form_fields.py
Labels: kind: release
