Repository cordada/lib-cl-sii-python, pull requests merged in 2022-02, with the labels that each got.

#269 chore: Add tool to automatically sort Python imports
  .isort.cfg
  Makefile
  cl_sii/cte/f29/data_models.py
  cl_sii/cte/f29/parse_datos_obj.py
  cl_sii/dte/data_models.py
  cl_sii/dte/parse.py
  cl_sii/libs/rows_processing.py
  cl_sii/libs/xml_utils.py
  cl_sii/rcv/data_models.py
  cl_sii/rcv/parse_csv.py
  cl_sii/rtc/data_models.py
  cl_sii/rtc/data_models_aec.py
  cl_sii/rtc/data_models_cesiones_periodo.py
  cl_sii/rtc/parse_aec.py
  cl_sii/rtc/xml_utils.py
  cl_sii/rut/crypto_utils.py
  requirements/test.txt
  scripts/canonicalize_xml_file.py
  scripts/clean_dte_xml_file.py
  scripts/example.py
  tests/test_cte_f29_parse_datos_obj.py
  tests/test_dte_data_models.py
  tests/test_dte_parse.py
  tests/test_extras_drf_fields.py
  tests/test_extras_mm_fields.py
  tests/test_libs_crypto_utils.py
  tests/test_libs_dataclass_utils.py
  tests/test_libs_encoding_utils.py
  tests/test_libs_json_utils.py
  tests/test_libs_mm_utils.py
  tests/test_libs_rows_processing.py
  tests/test_libs_tz_utils.py
  tests/test_libs_xml_utils.py
  tests/test_rcv_data_models.py
  tests/test_rcv_parse_csv.py
  tests/test_rtc_data_models.py
  tests/test_rtc_data_models_aec.py
  tests/test_rtc_parse_aec.py
  tests/test_rtc_xml_utils.py
  tests/test_rut_crypto_utils.py
Labels: task, component: other

#274 chore: Increase Dependabot's open pull request limit for `pip`
  .github/dependabot.yml
Labels: task

#273 requirements: Update 'Flake8'
  requirements/test.txt
Labels: dependencies

#292 chore: Increase Django REST Framework required maximum version to 3.13.x
  requirements/extras.txt
  setup.py
Labels: component: config, dependencies

#294 chore: Simplify organization of Python dependency manifests
  .circleci/config.yml
  README.rst
  requirements-dev.txt
  requirements.txt
  requirements/base.txt
  requirements/dev.txt
  requirements/extras.txt
  requirements/release.txt
  tox.ini
Labels: task

#272 Add 'Black' Python code formatter
  .black.cfg.toml
  Makefile
  cl_sii/cte/f29/data_models.py
  cl_sii/cte/f29/parse_datos_obj.py
  cl_sii/dte/constants.py
  cl_sii/dte/data_models.py
  cl_sii/dte/parse.py
  cl_sii/extras/dj_form_fields.py
  cl_sii/extras/mm_fields.py
  cl_sii/libs/crypto_utils.py
  cl_sii/libs/csv_utils.py
  cl_sii/libs/dataclass_utils.py
  cl_sii/libs/encoding_utils.py
  cl_sii/libs/json_utils.py
  cl_sii/libs/mm_utils.py
  cl_sii/libs/rows_processing.py
  cl_sii/libs/xml_utils.py
  cl_sii/rcv/constants.py
  cl_sii/rcv/data_models.py
  cl_sii/rcv/parse_csv.py
  cl_sii/rtc/constants.py
  cl_sii/rtc/data_models.py
  cl_sii/rtc/data_models_aec.py
  cl_sii/rtc/data_models_cesiones_periodo.py
  cl_sii/rtc/parse_aec.py
  cl_sii/rtc/xml_utils.py
  cl_sii/rut/__init__.py
  cl_sii/rut/crypto_utils.py
  requirements-dev.txt
  setup.py
  tests/test_cte_f29_data_models.py
  tests/test_cte_f29_parse_datos_obj.py
  tests/test_dte_constants.py
  tests/test_dte_data_models.py
  tests/test_dte_parse.py
  tests/test_extras_mm_fields.py
  tests/test_libs_crypto_utils.py
  tests/test_libs_csv_utils.py
  tests/test_libs_dataclass_utils.py
  tests/test_libs_encoding_utils.py
  tests/test_libs_io_utils.py
  tests/test_libs_mm_utils.py
  tests/test_libs_rows_processing.py
  tests/test_libs_tz_utils.py
  tests/test_libs_xml_utils.py
  tests/test_rcv_constants.py
  tests/test_rcv_data_models.py
  tests/test_rcv_parse_csv.py
  tests/test_rtc_data_models.py
  tests/test_rtc_data_models_aec.py
  tests/test_rtc_data_models_cesiones_periodo.py
  tests/test_rtc_xml_utils.py
  tests/test_rut.py
  tests/test_rut_crypto_utils.py
  tests/test_scripts_clean_dte_xml_file.py
Labels: task, dependencies
