Repository cordada/lib-cl-sii-python, pull requests merged in 2022-08, with the labels that each got.

#350 chore: Add code owners
  CODEOWNERS
Labels: task

#352 chore: Change Dependabot schedule interval from `weekly` to `monthly`
  .github/dependabot.yml
Labels: task

#355 chore: Add Make tasks for installation
  .circleci/config.yml
  Makefile
  README.rst
Labels: task

#356 chore(deps): bump marshmallow from 2.19.5 to 2.21.0
  requirements.txt
  tests/test_extras_mm_fields.py
Labels: dependencies

#359 chore: Add Git commit linter
  .github/workflows/git-commit-lint.yaml
  commitlint.config.js
Labels: task

#360 Update files for Git commit linter
  .bumpversion.cfg
  docs/project-maintenance.rst
Labels: task, component: config

#361 Release v0.18.0
  .bumpversion.cfg
  .circleci/config.yml
  .github/dependabot.yml
  .github/workflows/git-commit-lint.yaml
  CODEOWNERS
  HISTORY.rst
  Makefile
  README.rst
  cl_sii/__init__.py
  cl_sii/rut/crypto_utils.py
  commitlint.config.js
  docs/project-maintenance.rst
  requirements-dev.txt
  requirements.txt
  setup.py
  tests/test_extras_mm_fields.py
  tests/test_libs_crypto_utils.py
  tests/test_libs_xml_utils.py
Labels: task, kind: release

#362 Add information dashboard to readme
  HISTORY.md
  HISTORY.rst
  MANIFEST.in
  README.md
  README.rst
  docs/project-maintenance.rst
  setup.py
Labels: task, documentation

#364 chore(deps): bump typing-extensions from 4.0.1 to 4.3.0
  requirements-dev.txt
Labels: dependencies
