Repository cordada/lib-cl-sii-python, pull requests merged in 2023-09, with the labels that each got.

#534 Release v0.23.2
  .bumpversion.cfg
  HISTORY.md
  cl_sii/__init__.py
Labels: task, kind: release

#535 Deploy release v0.23.2
  .bumpversion.cfg
  .ecrc
  .editorconfig
  .github/dependabot.yml
  .github/workflows/ci.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
  .github/workflows/super-linter.yaml
  HISTORY.md
  cl_sii/__init__.py
  mypy.ini
  requirements-dev.txt
  requirements.in
  requirements.txt
  setup.py
Labels: task, kind: deploy

#536 chore(deps): Update `typing-extensions` from 4.3.0 to 4.7.1
  requirements-dev.txt
  requirements.txt
Labels: dependencies

#538 Fix errors reported by EditorConfig-Checker
  cl_sii/data/ref/factura_electronica/schemas-xml/.editorconfig
  tests/test_data/.editorconfig
Labels: bug

#540 Update pydantic from 1.10.12 to 2.3.0
  requirements.in
  requirements.txt
  setup.py
  src/cl_sii/dte/data_models.py
  src/cl_sii/dte/parse.py
  src/cl_sii/rcv/data_models.py
  src/cl_sii/rtc/data_models.py
  src/cl_sii/rtc/data_models_aec.py
  src/cl_sii/rtc/parse_aec.py
  src/tests/test_dte_data_models.py
  src/tests/test_rcv_data_models.py
  src/tests/test_rtc_data_models.py
  src/tests/test_rtc_data_models_aec.py
Labels: task, dependencies

#541 Release v0.23.3
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release
