Repository cordada/lib-cl-sii-python, pull requests merged in 2023-03, with the labels that each got.

#449 Drop support for Python 3.7
  .github/workflows/ci.yaml
  README.md
  mypy.ini
  requirements-dev.txt
  requirements.txt
  setup.py
  tox.ini
Labels: task, component: config, dependencies

#440 fix(cte): Add default values for known missing codes in SII CTE Form 29
  cl_sii/cte/f29/parse_datos_obj.py
  cl_sii/data/cte/f29_datos_obj_missing_key_fixes.json
  tests/test_cte_f29_parse_datos_obj.py
  tests/test_data/sii-cte/f29/cte--61002000-3--f29-6600000016-datos-obj-fake-missing-code-49.json
Labels: bug, component: cte

#450 Release v0.22.0
  .bumpversion.cfg
  HISTORY.md
  cl_sii/__init__.py
Labels: task, kind: release

#451 Deploy release v0.22.0
  .bumpversion.cfg
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
  HISTORY.md
  README.md
  cl_sii/__init__.py
  cl_sii/cte/f29/parse_datos_obj.py
  cl_sii/data/cte/f29_datos_obj_missing_key_fixes.json
  mypy.ini
  requirements-dev.in
  requirements-dev.txt
  requirements.txt
  setup.py
  tests/test_cte_f29_parse_datos_obj.py
  tests/test_data/sii-cte/f29/cte--61002000-3--f29-6600000016-datos-obj-fake-missing-code-49.json
  tox.ini
Labels: task, kind: release

#452 fix(data.cte): Add JSON files to MANIFEST.in
  MANIFEST.in
Labels: bug, component: cte

#453 Release v0.22.1
  .bumpversion.cfg
  HISTORY.md
  cl_sii/__init__.py
Labels: task, kind: release

#455 fix(data.cte): Add missing codes to files used by schema validator
  cl_sii/data/cte/f29_datos_obj_missing_key_fixes.json
Labels: bug, component: cte

#456 Release v0.22.2
  .bumpversion.cfg
  HISTORY.md
  cl_sii/__init__.py
Labels: task, kind: release

#457 Deploy release v0.22.2
  .bumpversion.cfg
  HISTORY.md
  cl_sii/__init__.py
  cl_sii/data/cte/f29_datos_obj_missing_key_fixes.json
  cl_sii/dte/parse.py
  cl_sii/libs/dataclass_utils.py
  cl_sii/libs/xml_utils.py
  cl_sii/rcv/data_models.py
  cl_sii/rcv/parse_csv.py
  requirements-dev.in
  requirements-dev.txt
  tests/test_dte_constants.py
  tests/test_extras_drf_fields.py
  tests/test_extras_mm_fields.py
  tests/test_libs_dataclass_utils.py
  tests/test_libs_io_utils.py
  tests/test_libs_json_utils.py
  tests/test_libs_xml_utils.py
  tests/test_rcv_parse_csv.py
  tests/test_rtc_constants.py
  tests/test_rut.py
Labels: task, kind: release

#458 fix(data.cte): Add missing code `8020` to file used by schema validator
  cl_sii/data/cte/f29_datos_obj_missing_key_fixes.json
Labels: bug, component: cte

#460 Deploy release v0.22.3
  .bumpversion.cfg
  HISTORY.md
  cl_sii/__init__.py
  cl_sii/data/cte/f29_datos_obj_missing_key_fixes.json
  requirements-dev.in
  requirements-dev.txt
Labels: task, kind: release

#462 Update minimum version of `signxml` to `3.1.0`
  setup.py
Labels: bug, dependencies

#463 Decrease Dependabot's open pull request limit to 5
  .github/dependabot.yml
Labels: task, component: config
