Repository cordada/lib-cl-sii-python, pull requests merged in 2023-07, with the labels that each got.

#502 chore(deps): Update `pip-tools` from 6.8.0 to 6.14.0
  Makefile
  requirements-dev.txt
  requirements.txt
Labels: dependencies

#513 chore(deps): Update `django` from 3.2.17 to 3.2.20
  requirements.txt
Labels: dependencies

#515 chore(deps): Update `certifi` from 2022.6.15 to 2023.7.22
  requirements-dev.txt
  requirements.txt
Labels: dependencies

#516 Update code owners
  CODEOWNERS
Labels: task

#517 Release v0.23.1
  .bumpversion.cfg
  HISTORY.md
  cl_sii/__init__.py
Labels: task, kind: release

#518 Deploy release v0.23.1
  .bumpversion.cfg
  .github/workflows/ci.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
  CODEOWNERS
  CONTRIBUTING.md
  HISTORY.md
  Makefile
  cl_sii/__init__.py
  cl_sii/libs/dataclass_utils.py
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
  setup.cfg
  tests/test_libs_crypto_utils.py
Labels: task, kind: deploy
