Repository cordada/lib-cl-sii-python, pull requests merged in 2023-04, with the labels that each got.

#218 Add data model for DTE Referencia
  cl_sii/base/constants.py
  cl_sii/dte/constants.py
  cl_sii/dte/data_models.py
  cl_sii/dte/parse.py
  tests/test_data/sii-crypto/DTE--96670340-7--61--110616-cert.der
  tests/test_data/sii-crypto/DTE--96670340-7--61--110616-cert.pem
  tests/test_data/sii-crypto/DTE--96670340-7--61--110616-signature-value-base64.txt
  tests/test_data/sii-dte/DTE--96670340-7--61--110616--cleaned.xml
  tests/test_data/sii-dte/DTE--96670340-7--61--110616.xml
  tests/test_dte_data_models.py
  tests/test_dte_parse.py
  tests/test_rtc_parse_aec.py
Labels: enhancement, component: dte

#461 Add contributing guidelines
  CONTRIBUTING.md
  docs/project-maintenance.rst
Labels: documentation

#476 Release v0.23.0
  .bumpversion.cfg
  HISTORY.md
  cl_sii/__init__.py
Labels: task, kind: release

#477 Deploy release v0.23.0
  .bumpversion.cfg
  .editorconfig
  .github/dependabot.yml
  .github/workflows/super-linter.yaml
  CONTRIBUTING.md
  HISTORY.md
  cl_sii/__init__.py
  cl_sii/base/constants.py
  cl_sii/dte/constants.py
  cl_sii/dte/data_models.py
  cl_sii/dte/parse.py
  cl_sii/libs/xml_utils.py
  cl_sii/rtc/xml_utils.py
  docs/project-maintenance.rst
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
  setup.py
  tests/test_data/sii-crypto/DTE--96670340-7--61--110616-cert.der
  tests/test_data/sii-crypto/DTE--96670340-7--61--110616-cert.pem
  tests/test_data/sii-crypto/DTE--96670340-7--61--110616-signature-value-base64.txt
  tests/test_data/sii-dte/DTE--96670340-7--61--110616--cleaned.xml
  tests/test_data/sii-dte/DTE--96670340-7--61--110616.xml
  tests/test_dte_data_models.py
  tests/test_dte_parse.py
  tests/test_libs_xml_utils.py
  tests/test_rtc_parse_aec.py
Labels: task, kind: deploy

#478 Fix Git alias `lg-github-pr-summary` in Contributing Guidelines
  CONTRIBUTING.md
Labels: bug, documentation

#479 Update code owners for Python dependencies
  CODEOWNERS
Labels: task

#483 Add Codecov to CI workflow
  .github/workflows/ci.yaml
  Makefile
  requirements-dev.in
  requirements-dev.txt
  setup.cfg
Labels: task, component: config
