Repository cordada/lib-cl-sii-python, pull requests merged in 2023-02, with the labels that each got.

#433 Improve type checking
  Makefile
  cl_sii/libs/tz_utils.py
  mypy.ini
  requirements-dev.in
  requirements-dev.txt
  setup.cfg
  tests/test_dte_constants.py
  tests/test_dte_data_models.py
  tests/test_dte_parse.py
  tests/test_libs_csv_utils.py
  tests/test_libs_dataclass_utils.py
  tests/test_libs_encoding_utils.py
  tests/test_libs_io_utils.py
  tests/test_libs_mm_utils.py
  tests/test_libs_rows_processing.py
  tests/test_rcv_constants.py
  tests/test_rcv_data_models.py
  tests/test_rtc_data_models.py
  tests/test_rtc_parse_aec.py
Labels: task

#434 Improve type checking
  cl_sii/libs/xml_utils.py
  mypy.ini
  requirements-dev.in
  requirements-dev.txt
Labels: task

#426 chore(deps): Bump marshmallow from 2.21.0 to 3.19.0
  cl_sii/extras/mm_fields.py
  cl_sii/libs/mm_utils.py
  cl_sii/libs/rows_processing.py
  cl_sii/rcv/parse_csv.py
  mypy.ini
  requirements-dev.txt
  requirements.in
  requirements.txt
  setup.py
  tests/test_extras_mm_fields.py
Labels: task, dependencies

#437 Release v0.20.0
  .bumpversion.cfg
  .github/workflows/dependency-review.yaml
  .markdownlint.yaml
  HISTORY.md
  Makefile
  cl_sii/__init__.py
  cl_sii/extras/mm_fields.py
  cl_sii/libs/csv_utils.py
  cl_sii/libs/mm_utils.py
  cl_sii/libs/rows_processing.py
  cl_sii/libs/tz_utils.py
  cl_sii/libs/xml_utils.py
  cl_sii/rcv/parse_csv.py
  mypy.ini
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
  setup.cfg
  setup.py
  tests/test_dte_constants.py
  tests/test_dte_data_models.py
  tests/test_dte_parse.py
  tests/test_extras_mm_fields.py
  tests/test_libs_csv_utils.py
  tests/test_libs_dataclass_utils.py
  tests/test_libs_encoding_utils.py
  tests/test_libs_io_utils.py
  tests/test_libs_mm_utils.py
  tests/test_libs_rows_processing.py
  tests/test_libs_xml_utils.py
  tests/test_rcv_constants.py
  tests/test_rcv_data_models.py
  tests/test_rtc_data_models.py
  tests/test_rtc_parse_aec.py
Labels: task, kind: release

#441 Switch CI/CD from CircleCI to GitHub Actions
  .bumpversion.cfg
  .circleci/config.yml
  .github/dependabot.yml
  .github/workflows/ci-cd.yaml
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
  Makefile
  README.md
  docs/project-maintenance.rst
Labels: task, component: config
