Repository cordada/lib-cl-sii-python, pull requests merged in 2023-10, with the labels that each got.

#553 Improve CI/CD workflows
  .github/workflows/ci-cd.yaml
  .github/workflows/ci.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/git-commit-lint.yaml
  .github/workflows/super-linter.yaml
Labels: task

#554 Enable GHA secrets inheritance so that Codecov token can be passed
  .github/workflows/ci-cd.yaml
Labels: bug

#552 Release v0.23.4
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#556 Deploy release v0.23.4
  .bumpversion.cfg
  .github/workflows/ci-cd.yaml
  .github/workflows/ci.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/deploy.yaml
  .github/workflows/git-commit-lint.yaml
  .github/workflows/release.yaml
  .github/workflows/super-linter.yaml
  HISTORY.md
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
  src/cl_sii/__init__.py
  src/cl_sii/dte/data_models.py
  src/cl_sii/dte/parse.py
  src/cl_sii/rcv/data_models.py
  src/cl_sii/rtc/data_models.py
  src/cl_sii/rtc/data_models_aec.py
  src/cl_sii/rtc/parse_aec.py
  src/tests/test_dte_data_models.py
  src/tests/test_rcv_data_models.py
  src/tests/test_rtc_data_models.py
  src/tests/test_rtc_data_models_aec.py
Labels: task, kind: deploy

#555 Fix GitHub code scanning alerts 'Clear-text logging of sensitive info'
  src/cl_sii/libs/xml_utils.py
  src/cl_sii/rtc/xml_utils.py
Labels: bug, component: libs, component: rtc
