Repository cordada/lib-cl-sii-python, pull requests merged in 2023-01, with the labels that each got.

#417 Release v0.19.0
  .black.cfg.toml
  .bumpversion.cfg
  .circleci/config.yml
  HISTORY.md
  Makefile
  README.md
  cl_sii/__init__.py
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
  setup.py
  tox.ini
Labels: task, kind: release

#422 Add GitHub Dependency Review
  .github/workflows/dependency-review.yaml
Labels: task, topic: security

#423 Improve GitHub Dependency Review
  .github/workflows/dependency-review.yaml
Labels: task

#425 Update Markdownlint configuration
  .markdownlint.yaml
Labels: task
