Repository cordada/lib-cl-sii-python, pull requests merged in 2023-11, with the labels that each got.

#557 dte: Improve validation error message in `DteXmlData.referencias`
  src/cl_sii/dte/data_models.py
  src/tests/test_dte_data_models.py
Labels: task, component: dte

#564 Remove Make task `python-wheel-install`
  Makefile
Labels: task

#566 Add Python project configuration
  pyproject.toml
Labels: task

#565 chore(deps): Update `pip-tools` from 6.14.0 to 7.3.0
  Makefile
  requirements-dev.in
  requirements-dev.txt
  requirements.txt
Labels: dependencies

#569 Release v0.24.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#570 Deploy release v0.24.0
  .bumpversion.cfg
  .github/workflows/ci.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
  HISTORY.md
  Makefile
  pyproject.toml
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
  src/cl_sii/__init__.py
  src/cl_sii/dte/data_models.py
  src/cl_sii/libs/xml_utils.py
  src/cl_sii/rtc/xml_utils.py
  src/tests/test_dte_data_models.py
Labels: task, kind: deploy
