Repository cordada/lib-cl-sii-python, pull requests merged in 2024-02, with the labels that each got.

#602 chore(deps): Update `lxml` from 4.9.4 to 5.1.0
  requirements.in
  requirements.txt
  setup.py
  src/tests/test_libs_xml_utils.py
Labels: dependencies

#603 Release v0.27.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#604 Deploy release v0.27.0
  .bumpversion.cfg
  .github/workflows/ci.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
  HISTORY.md
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
  setup.py
  src/cl_sii/__init__.py
  src/cl_sii/base/constants.py
  src/cl_sii/contribuyente/constants.py
  src/cl_sii/dte/constants.py
  src/cl_sii/dte/data_models.py
  src/cl_sii/extras/dj_form_fields.py
  src/cl_sii/extras/dj_model_fields.py
  src/cl_sii/extras/drf_fields.py
  src/cl_sii/extras/mm_fields.py
  src/cl_sii/libs/crypto_utils.py
  src/cl_sii/libs/dataclass_utils.py
  src/cl_sii/libs/rows_processing.py
  src/cl_sii/libs/tz_utils.py
  src/cl_sii/libs/xml_utils.py
  src/cl_sii/rcv/constants.py
  src/cl_sii/rcv/data_models.py
  src/cl_sii/rcv/parse_csv.py
  src/cl_sii/rtc/constants.py
  src/cl_sii/rut/__init__.py
  src/cl_sii/rut/constants.py
  src/tests/test_libs_xml_utils.py
Labels: task, kind: deploy

#606 fix: Add default value for missing codes in SII CTE Form 29
  src/cl_sii/data/cte/f29_datos_obj_missing_key_fixes.json
Labels: bug, component: cte

#609 Release v0.28.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#610 Deploy release v0.28.0
  .bumpversion.cfg
  HISTORY.md
  requirements-dev.txt
  requirements.in
  requirements.txt
  src/cl_sii/__init__.py
  src/cl_sii/data/cte/f29_datos_obj_missing_key_fixes.json
Labels: task, kind: deploy
