Repository cordada/lib-cl-sii-python, pull requests merged in 2024-09, with the labels that each got.

#695 deps: Update `pydantic` from 2.8.2 to 2.9.2
  requirements.in
  requirements.txt
Labels: dependencies

#696 extras: Add Pydantic type for `Rut`
  pyproject.toml
  src/cl_sii/extras/pydantic_types.py
  src/tests/test_extras_pydantic_types.py
Labels: enhancement

#697 cte: Close file object in `f29.parse_datos_obj`
  src/cl_sii/cte/f29/parse_datos_obj.py
Labels: bug, component: cte

#698 Release v0.33.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#699 Deploy release v0.33.0
  .bumpversion.cfg
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
  HISTORY.md
  pyproject.toml
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
  src/cl_sii/__init__.py
  src/cl_sii/cte/f29/parse_datos_obj.py
  src/cl_sii/extras/pydantic_types.py
  src/cl_sii/rut/crypto_utils.py
  src/tests/test_extras_pydantic_types.py
  src/tests/test_libs_crypto_utils.py
  src/tests/test_rut_crypto_utils.py
Labels: task, kind: deploy

#701 Enable type checking for `setuptools`
  mypy.ini
Labels: task

#702 Enable type checking for `lxml`
  mypy.ini
  requirements-dev.in
  requirements-dev.txt
  src/cl_sii/dte/parse.py
  src/cl_sii/libs/xml_utils.py
  src/cl_sii/rtc/parse_aec.py
Labels: task

#703 Relax some validations for trusted inputs
  src/cl_sii/dte/data_models.py
  src/cl_sii/rtc/parse_aec.py
  src/tests/test_dte_data_models.py
Labels: enhancement

#704 Release v0.34.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#705 Deploy release v0.34.0
  .bumpversion.cfg
  HISTORY.md
  mypy.ini
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
  src/cl_sii/__init__.py
  src/cl_sii/dte/data_models.py
  src/cl_sii/dte/parse.py
  src/cl_sii/libs/xml_utils.py
  src/cl_sii/rtc/parse_aec.py
  src/tests/test_dte_data_models.py
Labels: task, kind: deploy

#706 Improvements and fixes related to validation of trusted inputs
  src/cl_sii/dte/data_models.py
  src/cl_sii/dte/parse.py
  src/cl_sii/rtc/data_models_aec.py
  src/cl_sii/rtc/parse_aec.py
  src/tests/test_dte_data_models.py
Labels: bug, enhancement, component: dte, component: rtc

#582 Add configuration for ignoring revisions in Git Blame
  .git-blame-ignore-revs
Labels: task

#707 Make file `setup.py` executable again
  setup.py
Labels: bug

#708 Release v0.35.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#709 Deploy release v0.35.0
  .bumpversion.cfg
  .git-blame-ignore-revs
  HISTORY.md
  setup.py
  src/cl_sii/__init__.py
  src/cl_sii/dte/data_models.py
  src/cl_sii/dte/parse.py
  src/cl_sii/rtc/data_models_aec.py
  src/cl_sii/rtc/parse_aec.py
  src/tests/test_dte_data_models.py
Labels: task, kind: deploy
