Repository cordada/lib-cl-sii-python, pull requests merged in 2024-10, with the labels that each got.

#717 Refactor `cryptography.hazmat.*` Python imports
  src/cl_sii/libs/crypto_utils.py
  src/cl_sii/rut/crypto_utils.py
  src/tests/test_rut_crypto_utils.py
Labels: task

#716 Update cleaning regex to match RUTs with non-numeric digits
  src/cl_sii/rut/crypto_utils.py
  src/tests/test_data/sii-crypto/TEST-DTE-13185095-K.der
  src/tests/test_data/sii-crypto/TEST-DTE-13185095-K.pem
  src/tests/test_data/sii-crypto/TEST-DTE-WITH-ID-BUT-NO-RUT.der
  src/tests/test_data/sii-crypto/TEST-DTE-WITH-ID-BUT-NO-RUT.pem
  src/tests/test_data/sii-crypto/howto.md
  src/tests/test_rut_crypto_utils.py
Labels: bug, component: sii_crypto

#718 Release v0.36.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#719 Deploy release v0.36.0
  .bumpversion.cfg
  .github/workflows/ci.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
  HISTORY.md
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
  src/cl_sii/__init__.py
  src/cl_sii/libs/crypto_utils.py
  src/cl_sii/rut/crypto_utils.py
  src/tests/test_data/sii-crypto/TEST-DTE-13185095-K.der
  src/tests/test_data/sii-crypto/TEST-DTE-13185095-K.pem
  src/tests/test_data/sii-crypto/TEST-DTE-WITH-ID-BUT-NO-RUT.der
  src/tests/test_data/sii-crypto/TEST-DTE-WITH-ID-BUT-NO-RUT.pem
  src/tests/test_data/sii-crypto/howto.md
  src/tests/test_rut_crypto_utils.py
Labels: task, kind: deploy

#721 rut: Improve type annotation; Add method to validate DV
  src/cl_sii/rut/__init__.py
  src/tests/test_rut.py
Labels: enhancement, component: rut

#722 extras: Pydantic `Rut` type regex is not compliant with JSON Schema
  src/cl_sii/extras/pydantic_types.py
Labels: bug, component: rut

#723 Release v0.37.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#724 Deploy Release v0.37.0
  .bumpversion.cfg
  HISTORY.md
  requirements.txt
  src/cl_sii/__init__.py
  src/cl_sii/extras/pydantic_types.py
  src/cl_sii/rut/__init__.py
  src/tests/test_rut.py
Labels: task, kind: deploy

#726 chore(deps): Update `mypy` from 1.11.2 to 1.13.0
  requirements-dev.in
  requirements-dev.txt
Labels: dependencies

#727 Release v0.38.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#728 Deploy release v0.38.0
  .bumpversion.cfg
  HISTORY.md
  requirements-dev.in
  requirements-dev.txt
  src/cl_sii/__init__.py
  src/cl_sii/extras/pydantic_types.py
  src/tests/test_extras_pydantic_types.py
Labels: task, kind: deploy

#729 extras: Fix serialization of `None` in Pydantic `Rut` type
  src/cl_sii/extras/pydantic_types.py
  src/tests/test_extras_pydantic_types.py
Labels: bug, component: rut
