Repository cordada/lib-cl-sii-python, pull requests merged in 2024-07, with the labels that each got.

#655 chore(deps): Update package `zipp` from 3.8.1 to 3.19.2
  requirements-dev.txt
  requirements.txt
Labels: dependencies

#658 Release v0.30.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#659 Deploy release v0.30.0
  .bumpversion.cfg
  .github/workflows/ci.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
  HISTORY.md
  Makefile
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
  src/cl_sii/__init__.py
Labels: task, kind: deploy

#661 extras: Add `RutFilter` for Django views and DRF views
  mypy.ini
  requirements.in
  requirements.txt
  setup.py
  src/cl_sii/extras/dj_filters.py
  src/tests/test_extras_dj_filters.py
Labels: enhancement

#662 extras: Add Django URL path converter for RUT and Tipo DTE
  src/cl_sii/extras/dj_url_converters.py
  src/tests/test_extras_dj_url_converters.py
Labels: enhancement

#663 extras: Add mapping of Django model fields to DRF serializer fields
  src/cl_sii/extras/drf_serializers.py
  src/tests/test_extras_drf_serializers.py
Labels: enhancement

#664 extras: Reformat source code of `.dj_filters`
  src/cl_sii/extras/dj_filters.py
Labels: task

#665 Release v0.31.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#666 Deploy release v0.31.0
  .bumpversion.cfg
  HISTORY.md
  mypy.ini
  requirements.in
  requirements.txt
  setup.py
  src/cl_sii/__init__.py
  src/cl_sii/extras/dj_filters.py
  src/cl_sii/extras/dj_url_converters.py
  src/cl_sii/extras/drf_serializers.py
  src/tests/test_extras_dj_filters.py
  src/tests/test_extras_dj_url_converters.py
  src/tests/test_extras_drf_serializers.py
Labels: task, kind: deploy
