Repository cordada/lib-cl-sii-python, pull requests merged in 2025-03, with the labels that each got.

#782 Deploy release v0.43.0
  .black.cfg.toml
  .bumpversion.cfg
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
  HISTORY.md
  README.md
  mypy.ini
  pyproject.toml
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
  src/cl_sii/__init__.py
  src/cl_sii/libs/crypto_utils.py
  src/tests/test_libs_crypto_utils.py
  src/tests/test_libs_xml_utils.py
  src/tests/test_rut_crypto_utils.py
  tox.ini
Labels: task, kind: deploy

#783 deps: Update `packaging` from 24.1 to 24.2
  requirements-dev.txt
  requirements.txt
Labels: bug, dependencies

#785 Release v0.44.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#787 Require Python ≥3.9
  pyproject.toml
Labels: task

#788 Release v0.45.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#790 Add GitHub Actions workflow to release and deploy; Etc.
  .github/workflows/git-commit-lint.yaml
  .github/workflows/task-release-and-deploy.yaml
Labels: task
