Repository cordada/lib-cl-sii-python, pull requests merged in 2025-09, with the labels that each got.

#867 rcv: Update RCV CSV typing and RCV Ventas preprocessing
  src/cl_sii/rcv/parse_csv.py
  src/tests/test_rcv_parse_csv.py
Labels: enhancement, task, component: rcv, x-acct-type-dev-cap

#869 Release v0.53.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#871 rut: Use class variables for exception messages raised by `Rut`
  src/cl_sii/rut/__init__.py
Labels: task, component: rut

#874 extras: Add option to validate RUT DV to Django model field `RutField`
  src/cl_sii/extras/dj_model_fields.py
  src/tests/test_extras_dj_model_fields.py
Labels: enhancement, component: rut

#875 extras: Refactor `dj_form_fields.RutField.to_python()`
  src/cl_sii/extras/dj_form_fields.py
Labels: task, component: rut

#876 Release v0.54.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#878 extras: Improve Django filter for `Rut`
  src/cl_sii/extras/dj_filters.py
  src/tests/test_extras_dj_filters.py
Labels: enhancement, component: rut

#882 extras: Django model field `RutField` does not validate DV of `Rut`
  src/cl_sii/extras/dj_model_fields.py
  src/tests/test_extras_dj_model_fields.py
Labels: bug, component: rut

#886 Release v0.56.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#892 rcv: Improve checks for RCV Reclamado parser workaround
  src/cl_sii/rcv/parse_csv.py
  src/tests/test_data/sii-rcv/RCV-compra-reclamado.csv
  src/tests/test_rcv_parse_csv.py
Labels: bug, component: rcv

#890 cte: Add parser for "Datos del Contribuyente"
  src/cl_sii/cte/data_models.py
  src/cl_sii/cte/parsers.py
  src/tests/test_cte_parsers.py
  src/tests/test_data/sii-cte/cte_empty_f29.html
  src/tests/test_data/sii-cte/cte_empty_table.html
Labels: enhancement, component: cte, x-acct-type-dev-cap

#896 rut: Add regex for canonical RUT that is compatible with JSON Schema
  src/cl_sii/extras/pydantic_types.py
  src/cl_sii/rut/constants.py
  src/tests/test_rut_constants.py
Labels: enhancement, component: rut

#895 cte: Add parser for "Propiedades y Bienes Raíces"
  src/cl_sii/cte/data_models.py
  src/cl_sii/cte/parsers.py
  src/tests/test_cte_parsers.py
  src/tests/test_data/sii-cte/cte_empty_f29.html
Labels: enhancement, component: cte, x-acct-type-dev-cap

#897 Release v0.58.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#903 rcv: Fix Mypy errors in `test_rcv_parse_csv`
  mypy.ini
  src/tests/test_rcv_parse_csv.py
Labels: task, component: rcv
