Repository cordada/lib-cl-sii-python, pull requests merged in 2025-07, with the labels that each got.

#837 dte: Customize range of random folio in `DteNaturalKey.random()`
  src/cl_sii/dte/data_models.py
  src/tests/test_dte_data_models.py
Labels: enhancement, component: dte

#839 deps: Install Python package `setuptools`
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: task, dependencies

#840 deps: Uninstall Python package `wheel`
  pyproject.toml
  requirements-dev.in
  requirements-dev.txt
Labels: task, dependencies

#843 chore(task): Update editorconfig checker
  .editorconfig-checker.json
Labels: task
