Repository cordada/lib-cl-sii-python, pull requests merged in 2025-01, with the labels that each got.

#748 Use most recent patch version of Python in CI/CD configuration
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
Labels: task

#749 deps: Update dependency constraints of Python package `cl-sii`
  pyproject.toml
Labels: dependencies

#752 Release v0.40.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#754 Deploy release v0.40.0
  .bumpversion.cfg
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
  HISTORY.md
  pyproject.toml
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
  src/cl_sii/__init__.py
Labels: task, kind: deploy

#753 Exclude only individual test files in Mypy configuration
  mypy.ini
Labels: task

#755 Improve Make tasks `clean-build`, `clean-pyc`, and `clean-test`
  Makefile
Labels: task

#756 Release v0.41.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#757 Deploy release v0.41.0
  .bumpversion.cfg
  HISTORY.md
  Makefile
  mypy.ini
  src/cl_sii/__init__.py
Labels: task, kind: deploy

#758 Enable `warn_unused_ignores` in Mypy configuration
  mypy.ini
  src/cl_sii/extras/mm_fields.py
  src/cl_sii/libs/rows_processing.py
  src/cl_sii/libs/tz_utils.py
  src/cl_sii/rcv/parse_csv.py
  src/cl_sii/rtc/parse_aec.py
Labels: task

#759 Annotate method return types with `typing.Self` where appropriate
  pyproject.toml
  requirements.in
  requirements.txt
  src/cl_sii/dte/data_models.py
  src/cl_sii/rcv/data_models.py
  src/cl_sii/rtc/data_models.py
  src/cl_sii/rtc/data_models_aec.py
Labels: task

#761 deps: Increase minimum version of Python package `Django` to 4.2
  pyproject.toml
  requirements.in
  requirements.txt
Labels: dependencies

#760 rut: Add constant with lowest RUT for personas jurídicas
  src/cl_sii/rut/constants.py
Labels: enhancement, component: rut

#762 Release v0.42.0
  .bumpversion.cfg
  HISTORY.md
  src/cl_sii/__init__.py
Labels: task, kind: release

#763 Deploy release v0.42.0
  .bumpversion.cfg
  HISTORY.md
  mypy.ini
  pyproject.toml
  requirements.in
  requirements.txt
  src/cl_sii/__init__.py
  src/cl_sii/dte/data_models.py
  src/cl_sii/extras/mm_fields.py
  src/cl_sii/libs/rows_processing.py
  src/cl_sii/libs/tz_utils.py
  src/cl_sii/rcv/data_models.py
  src/cl_sii/rcv/parse_csv.py
  src/cl_sii/rtc/data_models.py
  src/cl_sii/rtc/data_models_aec.py
  src/cl_sii/rtc/parse_aec.py
  src/cl_sii/rut/constants.py
Labels: task, kind: deploy

#764 Python dependency sync check is never executed in CI/CD workflow
  .github/workflows/ci.yaml
Labels: bug
